[[redirects]]
from = "/future-food"
to = "https://www.scifiideas.com/alien-food-generator"
status = 301

[[redirects]]
from = "/sci-fi-character-name-generator/"
to = "https://www.scifiideas.com/sci-fi-character-name-generator/"
status = 301

[[redirects]]
from = "/sftg/"
to = "https://www.scifiideas.com/scifi-story-title-generator/"
status = 301

[[redirects]]
from = "/sci-fi-story-idea-generator/"
to = "https://www.scifiideas.com/story-idea-generator/"
status = 301


